### ISSUE TITLE
Tools not working in VSCodium

### ISSUE THREAD

**Issue by trijuc** [sisoe24/Nuke-Tools#2]
Hi,

I was triying to use your tools with the OSS version of VSCode [VSCodium](https://vscodium.com/) (to avoid the telemetry stuff from VSCode mainly).

Installing from .vsix file worked and I can see differentes option in the Command Palette, I can change the extension settings,... but whenever I tried to run a command I always get the same command not found error.

Seems like the extension is installed but not activated. I was able to get some extra infor form the logs.

```
[2022-06-13 13:14:39.505] [exthost] [info] ExtensionService#_doActivateExtension virgilsisoe.nuke-tools, startup: false, activationEvent: 'onStartupFinished'
[2022-06-13 13:14:39.558] [exthost] [error] Activating extension virgilsisoe.nuke-tools failed due to an error:
[2022-06-13 13:14:39.558] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'length')
	at Object.correctAnalysisPath (c:\Users\charlie\.vscode-oss\extensions\virgilsisoe.nuke-tools-0.6.1\out\stubs.js:103:44)
	at activate (c:\Users\charlie\.vscode-oss\extensions\virgilsisoe.nuke-tools-0.6.1\out\extension.js:16:17)
	at Function._callActivateOptional (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:88:17470)
	at Function._callActivate (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:88:17131)
	at c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:88:14945
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async _activate (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:8180)
	at async _waitForDepsThenActivate (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:8122)
	at async _initialize (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:7486)

```
I would love to use the extension with VSCodium. If I can help providing any other info or doing some testing let me know.

Thanks

**Comment by sisoe24** [comment]
Thanks for letting me know!

There is a problem with the stubs section. By commenting out the following code block, the extension loads properly:

```js
// comment out src/extension.ts:19
if (isPythonInstalled()) {
   correctAnalysisPath();
}
```

However, **the stubs files cannot be currently added** as it throws a different error. I will investigate this since I was planning to use Vscodium at some point.

**Comment by sisoe24** [comment]
Ok so the main issue is that NukeTools on VSCode uses `python.analysis.extratPaths` for the stubs files while VSCodium does not have this setting but it does have `python.autoComplete.extraPaths` which might be the same or a similar setting.

Meanwhile, you can package the extension yourself by changing the setting reference and it should work fine.

```js
// src/stubs.ts:127
// Change python.analysis to python.autoComplete
const config = vscode.workspace.getConfiguration("python.analysis");
```

Once I investigate a little bit more and make sure the settings are the same, I will check how to publish on openvsx and make the extension available for the VSCodium marketplace.

Let me know if you manage to make it work.

**Comment by sisoe24** [comment]
The problem was that VSCodium does not ship with Pylance as the language server for Python but uses Jedi instead.

Pylance uses `python.analysis.extraPaths` and Jedi uses `python.autoComplete.extraPaths` to add extra packages for the auto-complete. 

From NukeTools 0.6.2 both language servers are supported and the extension is also available on [openvsx](https://open-vsx.org/extension/virgilsisoe/nuke-tools).
